# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f6e7669e82eb322a66435f2f5d2f4e9baeb373613eba80908a2ffa444a3f567cea39e4554a8ce8776df2904d1e5a3e610d9f2eacbb2b04962cd6103df339c08

test:
  secret_key_base: d0711617b9d9b1a016067e18534dd569ea240d37295df8867bc1aeb9d4ecba81d8afa3dd3cd7fc097e577c528c855e1930e2b5404fdc1bffc061fcc37e47a657

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
